// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hznuxxizvizggzplvmuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bnV4eGl6dml6Z2d6cGx2bXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTIwMTUsImV4cCI6MjA1NjkyODAxNX0.FSq4kWDlVkdQuZZzlciPzLQoMDAiQ7ZARS7fLivlV-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);